<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventosSeeder extends Seeder
{
    public function run(): void
    {
        $ahora = now();

        DB::table('eventos')->insert([

            /* ── MÚSICA (cat 1) ───────────────────────────────────── */
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 1,
                'tipo_evento'             => 1,
                'titulo'                  => 'Vibez Summer Festival 2026',
                'descripcion'             => 'El mayor festival de música electrónica del verano. Cuatro escenarios, más de 30 artistas y una experiencia única.',
                'fecha_inicio'            => '2026-07-20 18:00:00',
                'fecha_fin'               => '2026-07-21 06:00:00',
                'ubicacion_nombre'        => 'Recinto Ferial de Madrid',
                'ubicacion_direccion'     => 'Av. del Partenón 5, 28042 Madrid',
                'latitud'                 => 40.4617500,
                'longitud'                => -3.6887700,
                'precio_base'             => 45.00,
                'aforo_maximo'            => 5000,
                'aforo_actual'            => 0,
                'edad_minima'             => 18,
                'es_gratuito'             => 0,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 1,
                'tipo_evento'             => 1,
                'titulo'                  => 'Noche Latina — Salsa & Reggaeton BCN',
                'descripcion'             => 'La noche más caliente de Barcelona. DJs en directo, zona de baile, cócteles tropicales y la mejor música latina de la escena actual.',
                'fecha_inicio'            => '2026-06-13 23:00:00',
                'fecha_fin'               => '2026-06-14 06:00:00',
                'ubicacion_nombre'        => 'Sala Razzmatazz, Barcelona',
                'ubicacion_direccion'     => 'Carrer dels Almogàvers 122, 08018 Barcelona',
                'latitud'                 => 41.3994400,
                'longitud'                => 2.1947300,
                'precio_base'             => 18.00,
                'aforo_maximo'            => 1500,
                'aforo_actual'            => 0,
                'edad_minima'             => 18,
                'es_gratuito'             => 0,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 1,
                'tipo_evento'             => 1,
                'titulo'                  => 'Indie Acoustic Night — Madrid',
                'descripcion'             => 'Una velada íntima con los mejores grupos indie del momento. Sonido acústico, ambiente acogedor y música que eriza la piel.',
                'fecha_inicio'            => '2026-05-30 20:30:00',
                'fecha_fin'               => '2026-05-30 23:59:00',
                'ubicacion_nombre'        => 'Sala El Sol, Madrid',
                'ubicacion_direccion'     => 'Calle Jardines 3, 28013 Madrid',
                'latitud'                 => 40.4175800,
                'longitud'                => -3.7023000,
                'precio_base'             => 12.00,
                'aforo_maximo'            => 300,
                'aforo_actual'            => 0,
                'edad_minima'             => 16,
                'es_gratuito'             => 0,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],

            /* ── CULTURA (cat 2) ──────────────────────────────────── */
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 2,
                'tipo_evento'             => 1,
                'titulo'                  => 'Arte Urbano — Exposición MOCO Barcelona',
                'descripcion'             => 'Recorrido inmersivo por las obras más rompedoras del arte urbano contemporáneo. Instalaciones interactivas y proyecciones gigantes.',
                'fecha_inicio'            => '2026-05-10 10:00:00',
                'fecha_fin'               => '2026-08-31 20:00:00',
                'ubicacion_nombre'        => 'MOCO Museum, Barcelona',
                'ubicacion_direccion'     => 'Carrer de Montcada 25, 08003 Barcelona',
                'latitud'                 => 41.3838000,
                'longitud'                => 2.1796000,
                'precio_base'             => 17.00,
                'aforo_maximo'            => 400,
                'aforo_actual'            => 0,
                'edad_minima'             => null,
                'es_gratuito'             => 0,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 2,
                'tipo_evento'             => 1,
                'titulo'                  => 'Festival de Teatro Contemporáneo Valencia',
                'descripcion'             => 'Tres días de teatro rompedor, performance y danza contemporánea con compañías de toda Europa. Entradas gratuitas para menores de 25.',
                'fecha_inicio'            => '2026-09-04 19:00:00',
                'fecha_fin'               => '2026-09-06 22:00:00',
                'ubicacion_nombre'        => 'Teatro Principal, Valencia',
                'ubicacion_direccion'     => 'Carrer de Barcas 15, 46002 Valencia',
                'latitud'                 => 39.4728000,
                'longitud'                => -0.3749000,
                'precio_base'             => 0.00,
                'aforo_maximo'            => 600,
                'aforo_actual'            => 0,
                'edad_minima'             => null,
                'es_gratuito'             => 1,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],

            /* ── DEPORTE (cat 3) ──────────────────────────────────── */
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 3,
                'tipo_evento'             => 1,
                'titulo'                  => 'Trail Running Montserrat 2026',
                'descripcion'             => 'Carrera de montaña por los senderos más espectaculares de Montserrat. 21 km de pura adrenalina con vistas increíbles.',
                'fecha_inicio'            => '2026-10-11 08:00:00',
                'fecha_fin'               => '2026-10-11 18:00:00',
                'ubicacion_nombre'        => 'Montserrat, Barcelona',
                'ubicacion_direccion'     => 'Monestir de Montserrat, 08691 Barcelona',
                'latitud'                 => 41.5929000,
                'longitud'                => 1.8358000,
                'precio_base'             => 25.00,
                'aforo_maximo'            => 500,
                'aforo_actual'            => 0,
                'edad_minima'             => 18,
                'es_gratuito'             => 0,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 3,
                'tipo_evento'             => 1,
                'titulo'                  => 'Torneo Street Basketball 3x3 — Madrid',
                'descripcion'             => 'Torneo callejero de basket 3x3 en la Caja Mágica. Categorías masculina, femenina y mixta. Premios en metálico para los ganadores.',
                'fecha_inicio'            => '2026-06-27 10:00:00',
                'fecha_fin'               => '2026-06-27 20:00:00',
                'ubicacion_nombre'        => 'Caja Mágica, Madrid',
                'ubicacion_direccion'     => 'Camino de Perales s/n, 28041 Madrid',
                'latitud'                 => 40.3810000,
                'longitud'                => -3.6868000,
                'precio_base'             => 5.00,
                'aforo_maximo'            => 2000,
                'aforo_actual'            => 0,
                'edad_minima'             => null,
                'es_gratuito'             => 0,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],

            /* ── GASTRONOMÍA (cat 4) ──────────────────────────────── */
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 4,
                'tipo_evento'             => 1,
                'titulo'                  => 'Mercado Gourmet Barceloneta — Street Food',
                'descripcion'             => 'El mercado de food trucks más vibrante de Barcelona. 40 puestos con cocinas del mundo, catas de vino, cócteles artesanales y música en directo.',
                'fecha_inicio'            => '2026-08-01 12:00:00',
                'fecha_fin'               => '2026-08-03 23:00:00',
                'ubicacion_nombre'        => 'Barceloneta, Barcelona',
                'ubicacion_direccion'     => 'Passeig de Joan de Borbó, 08003 Barcelona',
                'latitud'                 => 41.3785000,
                'longitud'                => 2.1890000,
                'precio_base'             => 0.00,
                'aforo_maximo'            => 3000,
                'aforo_actual'            => 0,
                'edad_minima'             => null,
                'es_gratuito'             => 1,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 4,
                'tipo_evento'             => 1,
                'titulo'                  => 'Cata de Vinos Jóvenes — La Rioja Experience',
                'descripcion'             => 'Cata guiada de 8 vinos de bodegas emergentes de La Rioja. Maridaje con pintxos. Ideal para amantes del vino que quieren aprender.',
                'fecha_inicio'            => '2026-07-04 19:00:00',
                'fecha_fin'               => '2026-07-04 22:00:00',
                'ubicacion_nombre'        => 'Espacio Logroño, Logroño',
                'ubicacion_direccion'     => 'Calle Portales 50, 26001 Logroño',
                'latitud'                 => 42.4664000,
                'longitud'                => -2.4440000,
                'precio_base'             => 30.00,
                'aforo_maximo'            => 60,
                'aforo_actual'            => 0,
                'edad_minima'             => 18,
                'es_gratuito'             => 0,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],

            /* ── NETWORKING (cat 5) ───────────────────────────────── */
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 5,
                'tipo_evento'             => 2,
                'titulo'                  => 'Networking Tech Summit Barcelona',
                'descripcion'             => 'Conferencia online para profesionales del sector tecnológico. Ponencias, mesas redondas y espacios de networking virtual.',
                'fecha_inicio'            => '2026-05-15 10:00:00',
                'fecha_fin'               => '2026-05-15 18:00:00',
                'ubicacion_nombre'        => null,
                'ubicacion_direccion'     => null,
                'latitud'                 => null,
                'longitud'                => null,
                'precio_base'             => 0.00,
                'aforo_maximo'            => 500,
                'aforo_actual'            => 0,
                'edad_minima'             => null,
                'es_gratuito'             => 1,
                'url_externa'             => 'https://techsummit.vibez.com',
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 5,
                'tipo_evento'             => 1,
                'titulo'                  => 'Meetup Emprendedores — Madrid StartUp Night',
                'descripcion'             => 'Noche de networking para emprendedores y startups. Pitches de 3 minutos, inversores, mentores y cenas en grupo. ¡Tu idea puede despegar aquí!',
                'fecha_inicio'            => '2026-06-04 19:00:00',
                'fecha_fin'               => '2026-06-04 23:00:00',
                'ubicacion_nombre'        => 'Google Campus Madrid',
                'ubicacion_direccion'     => 'Calle Moreno Nieto 2, 28005 Madrid',
                'latitud'                 => 40.4118000,
                'longitud'                => -3.7077000,
                'precio_base'             => 0.00,
                'aforo_maximo'            => 200,
                'aforo_actual'            => 0,
                'edad_minima'             => null,
                'es_gratuito'             => 1,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],

            /* ── TECNOLOGÍA (cat 6) ───────────────────────────────── */
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 6,
                'tipo_evento'             => 1,
                'titulo'                  => 'Hackathon VIBEZ — 48h de Innovación',
                'descripcion'             => '48 horas para transformar una idea en un producto real. Mentores, talleres, comida y un premio de 5.000€ para el equipo ganador.',
                'fecha_inicio'            => '2026-09-18 18:00:00',
                'fecha_fin'               => '2026-09-20 18:00:00',
                'ubicacion_nombre'        => 'Hub Tecnológico La Nave, Madrid',
                'ubicacion_direccion'     => 'Calle Cifuentes 5, 28021 Madrid',
                'latitud'                 => 40.3791000,
                'longitud'                => -3.6818000,
                'precio_base'             => 0.00,
                'aforo_maximo'            => 250,
                'aforo_actual'            => 0,
                'edad_minima'             => 16,
                'es_gratuito'             => 1,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 6,
                'tipo_evento'             => 1,
                'titulo'                  => 'IA & Creatividad — Taller Generative Art',
                'descripcion'             => 'Aprende a crear arte con inteligencia artificial. Workshop práctico con Midjourney, Stable Diffusion y herramientas de vídeo generativo.',
                'fecha_inicio'            => '2026-07-11 10:00:00',
                'fecha_fin'               => '2026-07-11 18:00:00',
                'ubicacion_nombre'        => 'Espacio Betahaus, Barcelona',
                'ubicacion_direccion'     => 'Carrer de Viladomat 174, 08015 Barcelona',
                'latitud'                 => 41.3819000,
                'longitud'                => 2.1542000,
                'precio_base'             => 40.00,
                'aforo_maximo'            => 40,
                'aforo_actual'            => 0,
                'edad_minima'             => null,
                'es_gratuito'             => 0,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],

            /* ── MODA (cat 7) ─────────────────────────────────────── */
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 7,
                'tipo_evento'             => 1,
                'titulo'                  => 'Jóvenes Diseñadores — Desfile FW 2026',
                'descripcion'             => 'La pasarela más alternativa de Madrid. 15 diseñadores emergentes presentan sus colecciones Otoño-Invierno 2026 en un espacio industrial único.',
                'fecha_inicio'            => '2026-11-06 20:00:00',
                'fecha_fin'               => '2026-11-06 23:30:00',
                'ubicacion_nombre'        => 'Matadero Madrid',
                'ubicacion_direccion'     => 'Paseo de la Chopera 14, 28045 Madrid',
                'latitud'                 => 40.3953000,
                'longitud'                => -3.6988000,
                'precio_base'             => 22.00,
                'aforo_maximo'            => 350,
                'aforo_actual'            => 0,
                'edad_minima'             => null,
                'es_gratuito'             => 0,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 7,
                'tipo_evento'             => 1,
                'titulo'                  => 'Vintage Market & Moda Sostenible BCN',
                'descripcion'             => 'Mercadillo de ropa vintage y marcas de moda sostenible. Más de 50 vendedores, talleres de upcycling y photocall. Entrada libre.',
                'fecha_inicio'            => '2026-05-23 11:00:00',
                'fecha_fin'               => '2026-05-24 20:00:00',
                'ubicacion_nombre'        => 'Palo Alto Market, Barcelona',
                'ubicacion_direccion'     => 'Carrer dels Pellaires 30, 08019 Barcelona',
                'latitud'                 => 41.4020000,
                'longitud'                => 2.2100000,
                'precio_base'             => 0.00,
                'aforo_maximo'            => 2000,
                'aforo_actual'            => 0,
                'edad_minima'             => null,
                'es_gratuito'             => 1,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],

            /* ── INFANTIL (cat 8) ─────────────────────────────────── */
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 8,
                'tipo_evento'             => 1,
                'titulo'                  => 'Festival Magia & Circo para Familias',
                'descripcion'             => 'Un espectáculo de magia, malabarismo y acrobacias pensado para toda la familia. Show de 90 minutos en un circo itinerante con carpa gigante.',
                'fecha_inicio'            => '2026-08-14 18:00:00',
                'fecha_fin'               => '2026-08-14 20:00:00',
                'ubicacion_nombre'        => 'Parque del Retiro, Madrid',
                'ubicacion_direccion'     => 'Plaza de la Independencia 7, 28001 Madrid',
                'latitud'                 => 40.4153000,
                'longitud'                => -3.6844000,
                'precio_base'             => 8.00,
                'aforo_maximo'            => 800,
                'aforo_actual'            => 0,
                'edad_minima'             => null,
                'es_gratuito'             => 0,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],
            [
                'organizador_id'          => 1,
                'categoria_evento_id'     => 8,
                'tipo_evento'             => 1,
                'titulo'                  => 'Taller de Robótica Infantil — FabLab Madrid',
                'descripcion'             => 'Niños de 7 a 14 años aprenden a programar robots con Lego Mindstorms. 3 horas de actividades guiadas, creatividad y diversión garantizada.',
                'fecha_inicio'            => '2026-06-20 10:00:00',
                'fecha_fin'               => '2026-06-20 13:00:00',
                'ubicacion_nombre'        => 'FabLab Madrid',
                'ubicacion_direccion'     => 'Calle Alameda 13, 28014 Madrid',
                'latitud'                 => 40.4116000,
                'longitud'                => -3.6922000,
                'precio_base'             => 15.00,
                'aforo_maximo'            => 30,
                'aforo_actual'            => 0,
                'edad_minima'             => null,
                'es_gratuito'             => 0,
                'url_externa'             => null,
                'contador_comparticiones' => 0,
                'estado'                  => 1,
                'fecha_creacion'          => $ahora,
                'fecha_actualizacion'     => null,
            ],

        ]);
    }
}
